# This is a basic workflow to help you get started with Actions

name: armTemplateDeployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
   ARMDeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Azure Login With a Service Principal Secret
        uses: Azure/login@v2.3.0
        with:
          creds: ${{secrets.AZURE_SP_GITHUBACTIONS_CRED}}
      - name: Deploy Azure Resource Manager (ARM) Template Resource Group rg-st-test-arm-github-001
        uses: Azure/arm-deploy@v2
        with: 
          scope: subscription
          subscriptionId: 7cee551f-1950-4649-9e19-387201663add
          region: UK South
          template: ./arm-templates/resourcegroup.json
          deploymentName: rg-st-test-arm-github-001
