# This is a basic workflow to help you get started with Actions

name: armTemplateDeployment

on:
  workflow_dispatch:

jobs:
   ARMDeploy:
    runs-on: ubuntu-latest

     steps:
      - uses: actions/checkout@v4

      - name: Run Azure Login With a Service Principal Secret
        uses: Azure/login@v2.3.0
        with:
          creds: ${{secrets.AZURE_SP_GITHUBACTIONS_CRED}}
