# This is a basic workflow to help you get started with Actions

name: armTemplateDeployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
   ARMDeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Azure Login With a Service Principal Secret
        uses: Azure/login@v2.3.0
        with:
          creds: ${{secrets.AZURE_SP_GITHUBACTIONS_CRED}}
      - name: Deploy Group with AZ CLI
        uses: Azure/cli@v2.1.0
        with:
          inlinescript: 
            az deployment sub what-if --location "UK South" --template-file ./arm-templates/resourcegroup.json